[project]
name = 'StacksGrantDAO'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.dao-grants]
path = 'contracts/dao-grants.clar'
clarity_version = 2
epoch = 2.5

[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
